### ISSUE TITLE
Error on iOS 5 (Could not instantiate class named NSLayoutConstraint)

### ISSUE THREAD

**Issue by aleufms** [gregwym/InformaticToolbar#1]
Turn off the autolayout on navigation controller of your example.

**Comment by gregwym** [comment]
Hi aleufms, 

Thanks for pointing that out. I have turned off the autolayout for the storyboard. 
https://github.com/gregwym/InformaticToolbar/commit/616634d0c9fc767593dc9795194aa3b0c572a1b7
