### ISSUE TITLE
Allow implementation on Navigation Bar

### ISSUE THREAD

**Issue by ghost** [gregwym/InformaticToolbar#2]
Hello!
I would love to use this in my app. I have a "Messages" type of viewcontroller setup that allows users to chat with each other. It is laid out identical to Apple's Messages native app. I would like to add the progress bar to the top nav bar when a user sends a message so they can see that status while they send it.

How would I implement your code to work with a navigation bar?
Would be nice if you added into your methods what object to add the items to?
i.e.
[ITProgressBarItemSet progressBarItemSetWithTitle:@"This is progress title. " addToBar:YOUR_BAR_HERE dismissTarget:self andAction:@selector(dismissBarItemSet:)];

**Comment by gregwym** [comment]
Hi @jhickman7 , 

Unfortunately, NavigationBar works different then the Toolbar. This lib cannot help you to manipulate the navigation items. 

Please look at http://developer.apple.com/library/ios/#documentation/uikit/reference/UINavigationItem_Class/Reference/UINavigationItem.html#//apple_ref/occ/instp/UINavigationItem/titleView which allow you to set a custom view to the navigation bar title. 

Something like [Customize navigation bar with title view](http://stackoverflow.com/questions/8433016/customize-navigation-bar-with-title-view) will work, 

```
UIView *iv = [[UIView alloc] initWithFrame:CGRectMake(0,0,32,32)];
 [iv setBackgroundColor:[UIColor whiteColor]];
  self.navigationItem.titleView = iv;
```

Thanks, 
Greg
